{
  "openapi": "3.0.0",
  "info":{

    "title": "Sample Nodejs API",
    "description": "This is a sample Nodejs API.",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:3000/",
      "description": "Development server"
    }
  ],
  "paths": {
    "/login": {
      "post": {
        "description": "Login",
        "tags": ["Login"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Login"
              },
              "examples": {
                "admin user" :{
                  "value" :{
                    "email": "admin@example.com",
                    "password": "12345"
                  }
                },
                "common user" :{
                  "value" :{
                    "email": "common@example.com",
                    "password": "12345"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/responses/Token"
                }
              }
            }
          }
        }
      }
    },
    "/users": {
      "post": {
        "description": "Create a user",
        "tags": ["Users"],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/User"
              },
              "examples": {
                "admin user" :{
                  "value" :{
                    "name": "administrator",
                    "email": "admin@example.com",
                    "password": "12345",
                    "admin": true
                  }
                },
                "common user" :{
                  "value" :{
                    "name": "common",
                    "email": "common@example.com",
                    "password": "12345",
                    "admin": false
                  }
                }
              }
            }
          }
        },
        "responses": {
          "400": {
            "description": "User already exists"
          },
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/responses/User"
                }
              }
            }
          }
        }
      },
      "get": {
        "description": "Get all users",
        "tags": ["Users"],
        "security": [{ "bearerAuth": []}],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/responses/User"
                }
              }
            }
          }
        }
      }
    },
    "/user/{id}": {
      "put": {
        "description": "Update a user",
        "tags": ["Users"],
        "security": [{ "bearerAuth": []}],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID of user to update",
            "required": true
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/User"
              },
              "examples": {
                "admin user" :{
                  "value" :{
                    "name": "administratorUpdated",
                    "email": "admin@example.com",
                    "password": "12345updated",
                    "admin": true
                  }
                },
                "common user" :{
                  "value" :{
                    "name": "commonWithAdmin",
                    "email": "common@example.com",
                    "password": "12345",
                    "admin": true
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/responses/User"
                }
              }
            }
          }
        }
      },
      "delete": {
        "description": "Delete a user",
        "tags": ["Users"],
        "security": [{ "bearerAuth": []}],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "ID of user to delete",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/responses/User"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Login": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          }
        }
      },
      "User": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "admin": {
            "type": "boolean"
          }
        }
      }
    },
    "responses":{
      "User":{
        "type": "object",
        "properties":{
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "password": {
            "type": "string"
          },
          "admin": {
            "type": "boolean"
          },
          "created_at": {
            "type": "string"
          },
          "updated_at": {
            "type": "string"
          }
        }
      },
      "Token":{
        "type": "string"
      }
    },
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }

}